import { useState, useEffect, useMemo } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";
import { formatPhone, formatName } from "@/lib/validations";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Switch } from "@/components/ui/switch";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Plus, Copy, Check, Trash2, Edit2, Users, Link as LinkIcon, Phone, Mail, Loader2 } from "lucide-react";

interface Vendedor {
  id: string;
  nome: string;
  telefone: string;
  email: string | null;
  codigo: string;
  ativo: boolean;
  created_at: string;
}

interface LeadCount {
  vendedor: string | null;
  count: number;
}

interface VendedoresManagerProps {
  leads: { vendedor: string | null }[];
}

export default function VendedoresManager({ leads }: VendedoresManagerProps) {
  const [vendedores, setVendedores] = useState<Vendedor[]>([]);
  const [loading, setLoading] = useState(true);
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [isDeleteOpen, setIsDeleteOpen] = useState(false);
  const [editingVendedor, setEditingVendedor] = useState<Vendedor | null>(null);
  const [vendedorToDelete, setVendedorToDelete] = useState<Vendedor | null>(null);
  const [copiedId, setCopiedId] = useState<string | null>(null);
  const [formData, setFormData] = useState({ nome: "", telefone: "", email: "" });
  const [saving, setSaving] = useState(false);
  const { toast } = useToast();

  // Count leads per vendedor
  const leadCounts = useMemo(() => {
    const counts: Record<string, number> = {};
    leads.forEach(lead => {
      if (lead.vendedor) {
        counts[lead.vendedor] = (counts[lead.vendedor] || 0) + 1;
      }
    });
    return counts;
  }, [leads]);

  useEffect(() => {
    fetchVendedores();
  }, []);

  const fetchVendedores = async () => {
    try {
      const { data, error } = await supabase
        .from("vendedores")
        .select("*")
        .order("nome");

      if (error) throw error;
      setVendedores(data || []);
    } catch (error) {
      console.error("Erro ao buscar vendedores:", error);
      toast({
        title: "Erro",
        description: "Não foi possível carregar os vendedores.",
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  const handleSave = async () => {
    if (!formData.nome.trim() || !formData.telefone.trim()) {
      toast({
        title: "Campos obrigatórios",
        description: "Preencha nome e telefone.",
        variant: "destructive",
      });
      return;
    }

    setSaving(true);
    try {
      if (editingVendedor) {
        // Update
        const { error } = await supabase
          .from("vendedores")
          .update({
            nome: formData.nome,
            telefone: formData.telefone,
            email: formData.email || null,
          })
          .eq("id", editingVendedor.id);

        if (error) throw error;
        toast({ title: "Vendedor atualizado!" });
      } else {
        // Create - codigo is auto-generated by trigger
        const { error } = await supabase
          .from("vendedores")
          .insert({
            nome: formData.nome,
            telefone: formData.telefone,
            email: formData.email || null,
            codigo: "temp", // Will be overwritten by trigger
          } as any);

        if (error) throw error;
        toast({ title: "Vendedor cadastrado!" });
      }

      setIsDialogOpen(false);
      setEditingVendedor(null);
      setFormData({ nome: "", telefone: "", email: "" });
      fetchVendedores();
    } catch (error) {
      console.error("Erro ao salvar vendedor:", error);
      toast({
        title: "Erro",
        description: "Não foi possível salvar o vendedor.",
        variant: "destructive",
      });
    } finally {
      setSaving(false);
    }
  };

  const handleToggleAtivo = async (vendedor: Vendedor) => {
    try {
      const { error } = await supabase
        .from("vendedores")
        .update({ ativo: !vendedor.ativo })
        .eq("id", vendedor.id);

      if (error) throw error;
      
      setVendedores(prev => 
        prev.map(v => v.id === vendedor.id ? { ...v, ativo: !v.ativo } : v)
      );
      
      toast({
        title: vendedor.ativo ? "Vendedor desativado" : "Vendedor ativado",
        description: vendedor.ativo 
          ? "O link do vendedor não funcionará mais." 
          : "O link do vendedor está ativo novamente.",
      });
    } catch (error) {
      console.error("Erro ao atualizar status:", error);
      toast({
        title: "Erro",
        description: "Não foi possível atualizar o status.",
        variant: "destructive",
      });
    }
  };

  const handleDelete = async () => {
    if (!vendedorToDelete) return;

    try {
      const { error } = await supabase
        .from("vendedores")
        .delete()
        .eq("id", vendedorToDelete.id);

      if (error) throw error;
      
      setVendedores(prev => prev.filter(v => v.id !== vendedorToDelete.id));
      toast({ title: "Vendedor excluído!" });
    } catch (error) {
      console.error("Erro ao excluir vendedor:", error);
      toast({
        title: "Erro",
        description: "Não foi possível excluir o vendedor.",
        variant: "destructive",
      });
    } finally {
      setIsDeleteOpen(false);
      setVendedorToDelete(null);
    }
  };

  const copyLink = async (vendedor: Vendedor) => {
    const baseUrl = window.location.origin;
    const link = `${baseUrl}/?v=${vendedor.codigo}`;
    
    try {
      await navigator.clipboard.writeText(link);
      setCopiedId(vendedor.id);
      setTimeout(() => setCopiedId(null), 2000);
      toast({ title: "Link copiado!" });
    } catch {
      toast({
        title: "Erro ao copiar",
        description: "Copie manualmente: " + link,
        variant: "destructive",
      });
    }
  };

  const openEditDialog = (vendedor: Vendedor) => {
    setEditingVendedor(vendedor);
    setFormData({
      nome: vendedor.nome,
      telefone: vendedor.telefone,
      email: vendedor.email || "",
    });
    setIsDialogOpen(true);
  };

  const openNewDialog = () => {
    setEditingVendedor(null);
    setFormData({ nome: "", telefone: "", email: "" });
    setIsDialogOpen(true);
  };

  if (loading) {
    return (
      <Card>
        <CardContent className="flex items-center justify-center py-12">
          <Loader2 className="w-6 h-6 animate-spin text-primary" />
        </CardContent>
      </Card>
    );
  }

  return (
    <>
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <CardTitle className="flex items-center gap-2 text-brand-blue">
              <Users className="w-5 h-5" />
              Vendedores ({vendedores.length})
            </CardTitle>
            <Button onClick={openNewDialog} className="gap-2">
              <Plus className="w-4 h-4" />
              Novo Vendedor
            </Button>
          </div>
        </CardHeader>
        <CardContent>
          {vendedores.length === 0 ? (
            <div className="text-center py-8 text-muted-foreground">
              <Users className="w-12 h-12 mx-auto mb-4 opacity-30" />
              <p>Nenhum vendedor cadastrado</p>
              <Button onClick={openNewDialog} variant="outline" className="mt-4">
                Cadastrar primeiro vendedor
              </Button>
            </div>
          ) : (
            <div className="overflow-x-auto">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Nome</TableHead>
                    <TableHead>Contato</TableHead>
                    <TableHead>Leads</TableHead>
                    <TableHead>Status</TableHead>
                    <TableHead>Link</TableHead>
                    <TableHead className="text-right">Ações</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {vendedores.map((vendedor) => (
                    <TableRow key={vendedor.id} className={!vendedor.ativo ? "opacity-50" : ""}>
                      <TableCell className="font-medium">{vendedor.nome}</TableCell>
                      <TableCell>
                        <div className="space-y-1">
                          <div className="flex items-center gap-1 text-sm">
                            <Phone className="w-3 h-3 text-muted-foreground" />
                            {vendedor.telefone}
                          </div>
                          {vendedor.email && (
                            <div className="flex items-center gap-1 text-sm text-muted-foreground">
                              <Mail className="w-3 h-3" />
                              {vendedor.email}
                            </div>
                          )}
                        </div>
                      </TableCell>
                      <TableCell>
                        <Badge variant="outline" className="bg-primary/10 text-primary border-primary/20">
                          {leadCounts[vendedor.codigo] || 0} leads
                        </Badge>
                      </TableCell>
                      <TableCell>
                        <div className="flex items-center gap-2">
                          <Switch
                            checked={vendedor.ativo}
                            onCheckedChange={() => handleToggleAtivo(vendedor)}
                          />
                          <span className={`text-sm ${vendedor.ativo ? "text-green-600" : "text-muted-foreground"}`}>
                            {vendedor.ativo ? "Ativo" : "Inativo"}
                          </span>
                        </div>
                      </TableCell>
                      <TableCell>
                        <Button
                          variant="outline"
                          size="sm"
                          onClick={() => copyLink(vendedor)}
                          className="gap-2"
                          disabled={!vendedor.ativo}
                        >
                          {copiedId === vendedor.id ? (
                            <Check className="w-3 h-3 text-green-600" />
                          ) : (
                            <Copy className="w-3 h-3" />
                          )}
                          {copiedId === vendedor.id ? "Copiado!" : "Copiar"}
                        </Button>
                      </TableCell>
                      <TableCell className="text-right">
                        <div className="flex items-center justify-end gap-2">
                          <Button
                            variant="ghost"
                            size="icon"
                            onClick={() => openEditDialog(vendedor)}
                          >
                            <Edit2 className="w-4 h-4" />
                          </Button>
                          <Button
                            variant="ghost"
                            size="icon"
                            className="text-destructive hover:text-destructive"
                            onClick={() => {
                              setVendedorToDelete(vendedor);
                              setIsDeleteOpen(true);
                            }}
                          >
                            <Trash2 className="w-4 h-4" />
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Add/Edit Dialog */}
      <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>
              {editingVendedor ? "Editar Vendedor" : "Novo Vendedor"}
            </DialogTitle>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <Label htmlFor="nome">Nome *</Label>
              <Input
                id="nome"
                value={formData.nome}
                onChange={(e) => setFormData(prev => ({ ...prev, nome: formatName(e.target.value) }))}
                placeholder="Nome do vendedor"
                maxLength={100}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="telefone">Telefone *</Label>
              <Input
                id="telefone"
                value={formData.telefone}
                onChange={(e) => setFormData(prev => ({ ...prev, telefone: formatPhone(e.target.value) }))}
                placeholder="(00) 00000-0000"
                maxLength={15}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="email">Email (opcional)</Label>
              <Input
                id="email"
                type="email"
                value={formData.email}
                onChange={(e) => setFormData(prev => ({ ...prev, email: e.target.value }))}
                placeholder="email@exemplo.com"
              />
            </div>
            {!editingVendedor && (
              <p className="text-sm text-muted-foreground">
                <LinkIcon className="w-3 h-3 inline mr-1" />
                O link único será gerado automaticamente após o cadastro.
              </p>
            )}
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setIsDialogOpen(false)}>
              Cancelar
            </Button>
            <Button onClick={handleSave} disabled={saving}>
              {saving && <Loader2 className="w-4 h-4 animate-spin mr-2" />}
              {editingVendedor ? "Salvar" : "Cadastrar"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Delete Confirmation */}
      <AlertDialog open={isDeleteOpen} onOpenChange={setIsDeleteOpen}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Excluir Vendedor</AlertDialogTitle>
            <AlertDialogDescription>
              Tem certeza que deseja excluir {vendedorToDelete?.nome}? 
              O link deixará de funcionar. Esta ação não pode ser desfeita.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancelar</AlertDialogCancel>
            <AlertDialogAction
              onClick={handleDelete}
              className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
            >
              Excluir
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </>
  );
}
